@extends('layouts.fr-single-master')

@section('fr.master.content')
    <h1>Category wise news</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia eum doloribus incidunt id, velit voluptatum iusto sint magni, voluptatibus quae voluptas, blanditiis veritatis a illo quos repudiandae molestias similique hic tempore vitae in. Ab, facere nostrum? Rerum qui fuga alias totam non veritatis magni consequatur corrupti praesentium aut ex unde ipsum itaque cum perferendis eum libero molestiae molestias iure, nesciunt saepe esse ab voluptas assumenda? Obcaecati, optio incidunt modi iusto sit error laborum qui ex laudantium commodi neque architecto harum quaerat minima suscipit eveniet voluptate hic, blanditiis, illum explicabo voluptatum. Dolores corporis dicta nesciunt ex error recusandae velit itaque illo accusantium sit atque debitis quam ab porro ipsam quaerat et voluptas id pariatur, doloribus, veritatis earum asperiores! Eius placeat eveniet beatae voluptatum velit non laborum quia consequuntur tenetur rem quis neque ut unde sint illum doloremque recusandae ipsam, quae nemo debitis officiis. Placeat illum amet commodi nostrum esse nisi hic.</p>
    {{-- comments --}}
    <h3>Comments</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus eum id recusandae iste enim, repellendus, harum necessitatibus sequi quidem deleniti modi corporis, vel nesciunt sint ea quae impedit nulla suscipit blanditiis placeat et at. Quas sequi fugiat itaque quasi iusto praesentium ab dolore dolorum! Expedita similique aliquam non autem incidunt?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus eum id recusandae iste enim, repellendus, harum necessitatibus sequi quidem deleniti modi corporis, vel nesciunt sint ea quae impedit nulla suscipit blanditiis placeat et at. Quas sequi fugiat itaque quasi iusto praesentium ab dolore dolorum! Expedita similique aliquam non autem incidunt?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus eum id recusandae iste enim, repellendus, harum necessitatibus sequi quidem deleniti modi corporis, vel nesciunt sint ea quae impedit nulla suscipit blanditiis placeat et at. Quas sequi fugiat itaque quasi iusto praesentium ab dolore dolorum! Expedita similique aliquam non autem incidunt?</p>
    <h3>Related Post</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus eum id recusandae iste enim, repellendus, harum necessitatibus sequi quidem deleniti modi corporis, vel nesciunt sint ea quae impedit nulla suscipit blanditiis placeat et at. Quas sequi fugiat itaque quasi iusto praesentium ab dolore dolorum! Expedita similique aliquam non autem incidunt?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus eum id recusandae iste enim, repellendus, harum necessitatibus sequi quidem deleniti modi corporis, vel nesciunt sint ea quae impedit nulla suscipit blanditiis placeat et at. Quas sequi fugiat itaque quasi iusto praesentium ab dolore dolorum! Expedita similique aliquam non autem incidunt?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus eum id recusandae iste enim, repellendus, harum necessitatibus sequi quidem deleniti modi corporis, vel nesciunt sint ea quae impedit nulla suscipit blanditiis placeat et at. Quas sequi fugiat itaque quasi iusto praesentium ab dolore dolorum! Expedita similique aliquam non autem incidunt?</p>
@endsection